### ISSUE TITLE
Bad ssh command, missing variables

### ISSUE THREAD

**Issue by gnouts** [aleksasiriski/rffmpeg-go#1]
Hi, I'm in the process of migrating to your jellyfin docker image with this rffmpeg, so actively debugging. I hope this is not too early to open this.

The rffmpeg fails because of the ssh connection. Everything is setup correctly and works when I try manually to ssh from jellyfin container to worker container. But in the `log_rffmpeg` I can see : 
```
DBG Remote command="/usr/bin/ssh -q -t -o ConnectTimeout=1 -o ConnectionAttempts=1 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPath=/run/ssh-%!r(MISSING)@%!h(MISSING):%!p(MISSING) -o ControlPersist=%!s(int=300) -i /config/rffmpeg/.ssh/id_rsa -p 2222 -o StrictHostKeyChecking=accept-new root@192.168.30.109 /usr/lib/jellyfin-ffmpeg/ffmpeg -version"
```
see `ControlPath` and `ControlPersist` have variables not rendered correctly I guess.

--- 

```
# docker-compose.yml snippet
version: '3'
services:
  jellyfin:
    image: ghcr.io/aleksasiriski/jellyfin-rffmpeg:v10.8.9-6
    restart: always
    volumes:
      - ./config:/config 
      - ./rffmpeg/rffmpeg.yml:/etc/rffmpeg/rffmpeg.yml 
      - ./rffmpeg/ssh:/config/rffmpeg/.ssh     # contains id_rsa and id_rsa.pub
      - /mnt/transcodes:/config/transcodes  # NFS share that get mounted to worker
      - /mnt/subtitles:/config/data/subtitles  # NFS share that get mounted to worker
    tmpfs:
      - /tmp

```
```
# rffmpeg.yml
---
program:
    log: "/config/log"
    debug: true
directories:
    #state: "/config/rffmpeg"
    persist: "/run"
    owner: root
    group: root
remote:
    user: root
    args: 
        - "-i"
        - "/config/rffmpeg/.ssh/id_rsa"
        - "-p"
        - "2222"
        - "-o"
        - "StrictHostKeyChecking=accept-new"

```

**Comment by aleksasiriski** [comment]
Thanks for opening this, it's definitely not early, I'll look into this straight away

**Comment by aleksasiriski** [comment]
You shoud remove `state` from your config and add `database: path:` since it's `/var` by default, but for docker you need it on `/config`. You can look at the file used [here](https://github.com/aleksasiriski/jellyfin-rffmpeg/blob/main/docker/rffmpeg.yml).

Also, I've just fixed this issue in v10.8.9-7

**Comment by gnouts** [comment]
I confirm this is fixed, thanks :+1:

**Comment by aleksasiriski** [comment]
> I confirm this is fixed, thanks 👍

Let me know how it works for you, it should be identical to the original but slightly faster (in terms of latency, transcoding will remain the same)

**Comment by gnouts** [comment]
I haven't done extensive test yet, but it felt fast enough for my use case, nearly as fast as my current jellyfin monolithic install. Original implementation was a bit slower indeed, but I definitely need to tweak my disk share as this is probably the bottleneck anyway.

**Comment by aleksasiriski** [comment]
> I haven't done extensive test yet, but it felt fast enough for my use case, nearly as fast as my current jellyfin monolithic install. Original implementation was a bit slower indeed, but I definitely need to tweak my disk share as this is probably the bottleneck anyway.

I hope you're using NFS for sharing, google some flags it could definitely improve performance (notable use NFSv4 and not v3, async won't work for workers writing since Jellyfin needs files immediately and if you have it enabled it will slow down the stream because of that)
