### ISSUE TITLE
Base Jellyfin Container Deprecated

### ISSUE THREAD

**Issue by seang96** [aleksasiriski/rffmpeg-go#24]
The parent container these are built off of are Deprecated from https://github.com/onedr0p/containers/commit/48ce870395b27148ce95e9289b874df14bbd9f1a. 

Since Jellyfin 10.8.13 just came out patching a vulnerability, this needs to be updated soon hopefully without breaking backwards compatibility with existing deployments.

**Comment by aleksasiriski** [comment]
I noticed this on 10.8.12, sadly I've been busy. I'm planning on doing this later this evening (will be switching to distroless image).

**Comment by seang96** [comment]
Nice, I appreciate the work! I was planning to look into this too but wasn't sure if I'd meet the recommended update deadline in time since I plan on redoing my cluster with some hardware upgrades.

**Comment by aleksasiriski** [comment]
Just to give an update:

- I'm in the process of switching to chainguard wolfi-os based images (they have dotnet variants)
- I will be deprecating [intro-skipper](https://github.com/ConfusedPolarBear/intro-skipper) since it's been archived and I personally stopped using it
- I will be moving this repository under my org named [tminaorg](https://github.com/tminaorg/containers)

**Comment by seang96** [comment]
Shame about inteo-skipper it does for work 10.8 still but someone forked it for 10.9. Someone else forked it and said in jellyfin forums that they were planning on maintaining it too.

**Comment by aleksasiriski** [comment]
> Shame about inteo-skipper it does for work 10.8 still but someone forked it for 10.9. Someone else forked it and said in jellyfin forums that they were planning on maintaining it too.

If you can give me a link to the maintained version, I will gladly use that and keep the intro-skipper Dockerfile

**Comment by seang96** [comment]
Looks like this [one](https://github.com/Bobby306/intro-skipper) is trying to maintain from where it left off. Then this is the [one](https://github.com/endrl/jellyfin-plugin-media-analyzer) where they are adding new stuff and renamed the plugin even, the second one also has an active PR to put it in jellyfin, https://github.com/jellyfin/jellyfin/pull/10530.
